#+TITLE: Mi Configuración de XMonad
#+AUTHOR: Pascual M.G.
#+DATE: [2024-03-17 Dom]

* Configuración de XMonad con Submódulos

Este repositorio contiene mi configuración personal de XMonad, incluyendo submódulos para xmonad y xmonad-contrib.

** Estructura del Repositorio

- xmonad.hs: Mi configuración personal de XMonad
- xmonad/: Submódulo del repositorio principal de XMonad
- xmonad-contrib/: Submódulo del repositorio de XMonad-Contrib
- stack.yaml: Configuración de Stack para compilar XMonad

** Configuración Inicial

Para configurar este repositorio desde cero:

1. importante clonarlo en ~/.config/xmonad

   #+begin_src bash
cd .config
git clone ...
git submodule update --init --recursive
   #+end_src
** Compilación

Para compilar XMonad con esta configuración:

#+begin_src bash
stack install
#+end_src

Por supuesto tienes que tener stack , recomiendo o ghcup o =nix-shell -p stack=


** Actualización de Submódulos

Para actualizar los submódulos a las últimas versiones:

#+begin_src bash
git submodule update --remote --merge
#+end_src


** Ventajas de esta Configuración

- Versionado de la configuración personal de XMonad
- Fácil actualización de xmonad y xmonad-contrib como submódulos
- Compilación directa desde el repositorio
- Replicación sencilla de la configuración en diferentes máquinas

** Notas Importantes

- Después de actualizar los submódulos, es necesario hacer un commit adicional en el repositorio principal para registrar los nuevos punteros de los submódulos.
- Asegúrate de tener instaladas las dependencias necesarias para compilar XMonad en tu sistema.

* Contribuciones

Siéntete libre de hacer fork de este repositorio y adaptarlo a tus necesidades. Si encuentras mejoras o correcciones, las pull requests son bienvenidas.

* Licencia
No hace falta , haz loque te de la gana xD
